alias xin='sudo xbps-install -S'
alias xup='sudo xbps-install -Su'
alias xre='sudo xbps-remove -R'
alias xcl='sudo xbps-remove -o'
alias xse='xbps-query -Rs'
alias xpi='xbps-query -RS'
alias vimrc="$EDITOR ~/.config/nvim/init.vim"
alias strc="$EDITOR ~/.suckless/st/config.h"
alias dwmrc="$EDITOR ~/.suckless/dwm/config.h"
alias zshrc="$EDITOR ~/.zshrc"
